-- public.avatar определение

-- Drop table

-- DROP TABLE public.avatar;

CREATE TABLE public.avatar (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"data" oid NULL,
	file_path varchar(255) NULL,
	file_size int8 NOT NULL,
	media_type varchar(255) NULL,
	student_id int8 NULL,
	CONSTRAINT avatar_pkey PRIMARY KEY (id),
	CONSTRAINT ukoqwewcy88n5gdu8w8lipi9d06 UNIQUE (student_id)
);


-- public.avatar внешние включи

ALTER TABLE public.avatar ADD CONSTRAINT fkm6mgi7ty5gienen5rege7rc22 FOREIGN KEY (student_id) REFERENCES public.student(id);